### PR TITLE
Ignore Intellij/PyCharm project files

### PR DESCRIPTION
**Pull request by joshmoore**
Added to .gitinore:
```
*.iml
.idea
```

see #58 and #59

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Josh! 🙏

Are we interested in [ignoring these too]( https://github.com/github/gitignore/blob/e5323759e387ba347a9d50f8b0ddd16502eb71d4/Maven.gitignore )? Or are those not something we need to worry about?

**Comment by joshmoore** [comment]
Guess I'm a bit hesitant to try to capture all the possible builds and tools. I'd be inclined to wait until others rear their head, but if you'd prefer: happy to add Maven etc. here.

Sidenote: I'm going to ignore the build failure since I'm working on a more general solution in #57

**Comment by jakirkham** [comment]
Should we go ahead and merge?

**Comment by jakirkham** [comment]
Going to go ahead and merge since this is a useful change on its own and CI isn't related

**Pull request merged**
