### PR TITLE
Automatically generate test matrix

### PR DESCRIPTION
**Pull request by clbarnes**
With up to 4 libraries to test against each other, manually writing each test didn't look much fun.

Using pytest, you can dynamically generate which tests need to be run, correctly fail individual tests on missing dependencies, and so on. Pytest is great. This minimises the boilerplate which needs to be written for each new codec, library, or format.

Also contains changes from #9.

### CODE REVIEW

**Comment by clbarnes** [comment]
Yeah, I can do that!

**Comment by constantinpape** [comment]
> Worth noting that not all of the new tests pass - do the old ones?

Yeah, I think that not all of them are passing either. I will double check later and also look into setting up gh actions to have some CI.

**Comment by clbarnes** [comment]
I was just writing a travis file! Happy to leave it if you'd prefer to use Actions.

**Comment by constantinpape** [comment]
> I was just writing a travis file! Happy to leave it if you'd prefer to use Actions.

Yeah, I started to switch to actions; I find it a bit more convenient. I will add the workflow later :).
(And we can merge this PR before having CI)

**Pull request merged**
