### PR TITLE
Jacinth esther

### PR DESCRIPTION
**Pull request by JacinthEsther**

### CODE REVIEW

**Comment by jakirkham** [comment]
@JacinthEsther could you please pull latest `main` and commit your changes on top of that?

**Comment by JacinthEsther** [comment]
okay

**Comment by JacinthEsther** [comment]
I created a PR already and wanted to confirm if i have just the files wanted

**Comment by jakirkham** [comment]
PR ( https://github.com/zarr-developers/zarr_implementations/pull/62 )? Yeah it looks better to me, but Josh will know more. Will let him follow up there :)

**Comment by JacinthEsther** [comment]
okay

**Pull request closed without merging**
